events {}

http {
    upstream backend {
        server api:8000;    # "api" = docker service name, port 8000
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}